language: java
sudo: required
services:
- docker
script: mvn clean compile install fabric8:build
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
env:
  secure: dirVRWIrwdK+EB6RJfZsRlIkr65xv1eW53aCuQTM3JeZzqsMPo6iiRAOMHYDIoij9khOItH6TCr5TwFC41GZR6DqJ3XLEbfNEN5IcW/zgIERd8SnK6rgsKfL8ZQuaEU10WTLtM9uXa2IcfaZsOBKqbAqPYbRXVBf0SVO0bwoeFHSZwujuS2PtPkY2kWit5OmrGGtoXe25LxR6+tY0HUgSlsuv311MKiT1GCB8ypdYtBQnCRweRVQdo9n/oR4VkgMxk4LKFOkAPZ8FAt+3P1HWa9Gh9WAqvUMWV3OzBV1zovIjJbIdiYKXc9nMUPyC7QMNZBdiChyrvNEvlJQKHY49x38d0IlkQ/Q8mHVkrKBz+SLKmBf45/m2/9MYAQu0SzH3QQLZqcax+6oAKw+ODgP9HW4YZr8ybNfSMcsid34NU8hVZxWrjy8gIKGt74JqfO541u1SpXyKABj8p+BnoN17eWSP+0+vY9AmKzVkxc9tdcDIEQALNe4yz1iyd31QHi6MwDJxPlq6xenAsO9NSeMmmbLg9E4jyQBnF9dWTqzP0SDJCuKAYgdoOEZ61rI/Tdeig+mGf1UoCvCok6tacLkH+VnVMYK/zCAio53Z9B5ctwwkFsCyBh3/+KC1k/xd/XE1KVktBog3ZFfuzxccrtOxqOCV0t4m5l370szBbTu4CY=
